### ISSUE TITLE
When I use it with Foreman in devel env and I try to edit the organization, I'm getting 500

### ISSUE THREAD

**Issue by ares** [ofedoren/apipie-dsl#3]
I have no idea how the code can get activated, however it happens when I enter organization edit form, it seems the delegator is somehow affected by apipie-dsl

```
.vendor/ruby/2.5.0/bundler/gems/apipie-dsl-d06607e2448f/lib/apipie_dsl/dsl.rb:346:in `block in define_validators'
app/models/host/base.rb:100:in `domain_id'
.vendor/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/relation/delegation.rb:41:in `each'
.vendor/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/relation/delegation.rb:41:in `each'
app/services/tax_host.rb:151:in `map'
app/services/tax_host.rb:151:in `block (2 levels) in <class:TaxHost>'
app/services/tax_host.rb:216:in `block in default_ids_hash'
app/services/tax_host.rb:215:in `each'
app/services/tax_host.rb:215:in `default_ids_hash'
app/services/tax_host.rb:22:in `used_ids'
app/services/tax_host.rb:77:in `block in need_to_be_selected_ids'
app/services/tax_host.rb:73:in `map'
app/services/tax_host.rb:73:in `need_to_be_selected_ids'
app/services/tax_host.rb:129:in `check_for_orphans'
app/models/taxonomy.rb:213:in `check_for_orphans'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:605:in `catch'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:605:in `block in default_terminator'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `each'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `invoke_before'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_run_validate_callbacks'
.vendor/ruby/2.5.0/gems/activemodel-5.2.1/lib/active_model/validations.rb:409:in `run_validations!'
.vendor/ruby/2.5.0/gems/activemodel-5.2.1/lib/active_model/validations/callbacks.rb:118:in `block in run_validations!'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_run_validation_callbacks'
.vendor/ruby/2.5.0/gems/activemodel-5.2.1/lib/active_model/validations/callbacks.rb:118:in `run_validations!'
.vendor/ruby/2.5.0/gems/activemodel-5.2.1/lib/active_model/validations.rb:339:in `valid?'
.vendor/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/validations.rb:67:in `valid?'
app/views/taxonomies/edit.html.erb:3:in `_1716004831d140d6166198be96a6b78d'
.vendor/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/template.rb:159:in `block in render'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'
.vendor/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/template.rb:354:in `instrument_render_template'
.vendor/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/template.rb:157:in `render'
.vendor/ruby/2.5.0/gems/deface-1.5.3/lib/deface/action_view_extensions.rb:43:in `render'
.vendor/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
.vendor/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `instrument'
.vendor/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
.vendor/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
.vendor/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
.vendor/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
.vendor/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/template_renderer.rb:16:in `render'
.vendor/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/renderer.rb:44:in `render_template'
.vendor/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/renderer.rb:25:in `render'
.vendor/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/rendering.rb:103:in `_render_template'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/streaming.rb:219:in `_render_template'
.vendor/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/rendering.rb:84:in `render_to_body'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/rendering.rb:25:in `render'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/rendering.rb:36:in `render'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/opt/rh/rh-ruby25/root/usr/share/ruby/benchmark.rb:308:in `realtime'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
.vendor/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:45:in `render'
app/controllers/concerns/foreman/controller/taxonomies_controller.rb:67:in `block in edit'
app/models/taxonomy.rb:61:in `block in no_taxonomy_scope'
app/models/taxonomy.rb:68:in `block (2 levels) in as_taxonomy'
app/models/concerns/foreman/thread_session.rb:195:in `as_location'
app/models/taxonomy.rb:67:in `block in as_taxonomy'
app/models/concerns/foreman/thread_session.rb:154:in `as_org'
app/models/taxonomy.rb:66:in `as_taxonomy'
app/models/taxonomy.rb:60:in `no_taxonomy_scope'
app/controllers/concerns/foreman/controller/taxonomies_controller.rb:65:in `edit'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:194:in `process_action'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
app/controllers/concerns/foreman/controller/timezone.rb:10:in `set_timezone'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
app/controllers/concerns/foreman/controller/topbar_sweeper.rb:12:in `set_topbar_sweeper_controller'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
.vendor/ruby/2.5.0/gems/audited-4.9.0/lib/audited/sweeper.rb:14:in `around'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
.vendor/ruby/2.5.0/gems/audited-4.9.0/lib/audited/sweeper.rb:14:in `around'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `instrument'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
.vendor/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:134:in `process'
.vendor/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/rendering.rb:32:in `process'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal.rb:191:in `dispatch'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal.rb:252:in `dispatch'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:34:in `serve'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:52:in `block in serve'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:35:in `each'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:35:in `serve'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:840:in `call'
/home/vagrant/katello/lib/katello/middleware/event_daemon.rb:10:in `call'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/static.rb:127:in `call'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/static.rb:127:in `call'
.vendor/ruby/2.5.0/bundler/gems/apipie-dsl-d06607e2448f/lib/apipie_dsl/static_dispatcher.rb:67:in `call'
.vendor/ruby/2.5.0/gems/apipie-rails-0.5.17/lib/apipie/static_dispatcher.rb:66:in `call'
.vendor/ruby/2.5.0/gems/bullet-6.1.0/lib/bullet/rack.rb:15:in `call'
.vendor/ruby/2.5.0/gems/apipie-rails-0.5.17/lib/apipie/extractor/recorder.rb:137:in `call'
lib/foreman/middleware/telemetry.rb:10:in `call'
.vendor/ruby/2.5.0/gems/apipie-rails-0.5.17/lib/apipie/middleware/checksum_in_headers.rb:27:in `call'
lib/foreman/middleware/catch_json_parse_errors.rb:9:in `call'
.vendor/ruby/2.5.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
.vendor/ruby/2.5.0/gems/rack-2.1.1/lib/rack/tempfile_reaper.rb:17:in `call'
.vendor/ruby/2.5.0/gems/rack-2.1.1/lib/rack/etag.rb:27:in `call'
.vendor/ruby/2.5.0/gems/rack-2.1.1/lib/rack/conditional_get.rb:27:in `call'
.vendor/ruby/2.5.0/gems/rack-2.1.1/lib/rack/head.rb:14:in `call'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
lib/foreman/middleware/logging_context_session.rb:22:in `call'
.vendor/ruby/2.5.0/gems/rack-2.1.1/lib/rack/session/abstract/id.rb:277:in `context'
.vendor/ruby/2.5.0/gems/rack-2.1.1/lib/rack/session/abstract/id.rb:271:in `call'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/cookies.rb:670:in `call'
.vendor/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:559:in `call'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
.vendor/ruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:38:in `call_app'
.vendor/ruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:28:in `call'
.vendor/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
lib/foreman/middleware/logging_context_request.rb:11:in `call'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/home/vagrant/katello/lib/katello/prevent_json_parsing.rb:12:in `call'
.vendor/ruby/2.5.0/gems/rack-2.1.1/lib/rack/method_override.rb:24:in `call'
.vendor/ruby/2.5.0/gems/rack-2.1.1/lib/rack/runtime.rb:24:in `call'
.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
.vendor/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/static.rb:127:in `call'
.vendor/ruby/2.5.0/gems/rack-2.1.1/lib/rack/sendfile.rb:113:in `call'
.vendor/ruby/2.5.0/gems/secure_headers-6.3.0/lib/secure_headers/middleware.rb:11:in `call'
.vendor/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:524:in `call'
.vendor/ruby/2.5.0/gems/railties-5.2.1/lib/rails/railtie.rb:190:in `public_send'
.vendor/ruby/2.5.0/gems/railties-5.2.1/lib/rails/railtie.rb:190:in `method_missing'
.vendor/ruby/2.5.0/gems/rack-2.1.1/lib/rack/urlmap.rb:77:in `block in call'
.vendor/ruby/2.5.0/gems/rack-2.1.1/lib/rack/urlmap.rb:61:in `each'
.vendor/ruby/2.5.0/gems/rack-2.1.1/lib/rack/urlmap.rb:61:in `call'
.vendor/ruby/2.5.0/gems/puma-4.3.1/lib/puma/configuration.rb:228:in `call'
.vendor/ruby/2.5.0/gems/puma-4.3.1/lib/puma/server.rb:681:in `handle_request'
.vendor/ruby/2.5.0/gems/puma-4.3.1/lib/puma/server.rb:472:in `process_client'
.vendor/ruby/2.5.0/gems/puma-4.3.1/lib/puma/server.rb:328:in `block in run'
.vendor/ruby/2.5.0/gems/puma-4.3.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
.vendor/ruby/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Comment by ofedoren** [comment]
I've tried the latest version, this is no longer reproducible (at least I couldn't).
